name: flutter_dev_test
description: "Developer's Flutter test"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  http_mock_adapter: ^0.6.1
  flutter_bloc: ^8.1.6
  flutter_modular: ^6.3.4
  flutter_otp_text_field: ^1.2.0
  otp: ^3.1.4
  flutter_svg: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  

flutter:
  uses-material-design: true

  fonts:
    - family: PlusJakartaSans
      fonts:
      - asset: assets/fonts/PlusJakartaSans-Light.ttf
      - asset: assets/fonts/PlusJakartaSans-Regular.ttf
        weight: 300
      - asset: assets/fonts/PlusJakartaSans-Medium.ttf
        weight: 500
      - asset: assets/fonts/PlusJakartaSans-Bold.ttf
        weight: 700



  assets:
      - assets/fonts/
      - assets/img/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
